set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MSVC)
set(VCPKG_TARGET_IS_WINDOWS "1")
set(ENV{CC} clang)
set(ENV{CXX} clang++)